[pytest]
addopts = -v -s --junitxml=results/junit.xml

# Set the python path to the 'src' directory
pythonpath = src

# Include both 'unit' and 'integration' test paths
testpaths = test/unit test/integration

filterwarnings =
    ignore::DeprecationWarning
    error::RuntimeWarning

log_cli = true
log_cli_level = INFO

markers =
    smoke: smoke test cases
    regression: regression test cases


python_files = test_*.py *_test.py
python_classes = Test* *Test
python_functions = test_*